### ISSUE TITLE
Autocomplete and Search plugins need to work together

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#108]
Currently, the autocomplete plugin return the number of documents attached to each suggestions.
But if you perform a search with a suggested term, the number of results will be different from the autocomplete. 
I think it's better if the autocomplete suggestions show the same number of document as the search return.

**Comment by ebursztein** [comment]
I don't think it is technically possible as they try to achieve different goals. I did reworked the full stack to allows as much consistency as possible but there is case where it won't work.
