### ISSUE TITLE
Get the post type

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#110]
I need to be able to retreive the post type in these two cases:

- From a search result (currently there is no way to get the post type: https://i.gyazo.com/e72d9139c6483f373d9ca7bc0e4ca82e.png)

- From a post object in a template context (it's maybe already possible with the "template" frontmatter?)

Goal: https://i.gyazo.com/d61ec5435b5aba33939009503b358b84.png

**Comment by ebursztein** [comment]
Fixed by adding a "type" field, in the list. It is the name of the template.
