### ISSUE TITLE
Allow to get category/tag URL from EVERY templates

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#128]
Something like this could be fine:

![img](https://i.imgur.com/T1I9UyV.png)

**Comment by MarlBurroW** [comment]
It works now when i'm in a collection context, I can get the name and the url with meta.name and meta.url.

but the goal of this is issue is to accessing the category/tag URL from outside a collection page.

For example, in the blog post page or publication page, there is a breadcrumb with the category name, or some tags at the bottom (or the Show All button on the homepage). 
And I need to link them to the corresponding collection page.

What I need is something like this:

{{ collections['category-name-or-tag-name'].meta.url  }}

It's maybe already possible since the last commit ? Didn't see anything like this in the doc.

Thanks

**Comment by ebursztein** [comment]
Fixed the code so you can indeed get it as follow:
`{{categories[meta.category].meta.url}}`

Also updated the doc post_template to reflect this.
