### ISSUE TITLE
Thumbnail plugin - Only the first duplicated image is generated

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#157]
Hello,

Some posts has exactly the same image with different names, in this case the thumbnail plugin seems to generate only the first one (or the last one I don't really know). Probably caused by a hash check or something.

**Comment by ebursztein** [comment]
Can you provide an example so I can reproduce?

**Comment by MarlBurroW** [comment]
Tested and solved, thanks
