### ISSUE TITLE
Unexpected <p> tag in the ouput of the blockquote custom parser

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#174]
There is an unexpected `<p>` tag in the {{ text }} output.

Template:
```html
<blockquote>
  {{ text }}
</blockquote>
<a href="https://twitter.com/share?via=elie&text={{ text }}"  target="_blank" rel="noopener">Twitter</a>
```
Output
```html
<blockquote>
  <p>myblockquotetext</p>
</blockquote>
<a href="https://twitter.com/share?via=elie&text=<p>myblockquotetext</p>" target="_blank" rel="noopener">Twitter</a>
```
I have a work around, I use the "striptags" jinja filter to remove html, but I think it's better to  have just the text in the {{ text }} variable. What do you think ?
```

**Comment by ebursztein** [comment]
Work as intended, HTML spec says it is normal to . have text in a paragraph
