### ISSUE TITLE
meta.permanent_url doesn't return an absolute path

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#77]
The path returned by the post.meta.permanent_url is not absolute:

`<a href="{{ post.meta.permanent_url }}">post</a> `
rendered html:
`<a href="permanent-url-of-the-post">post</a> `

This link doesn't works when we are not located at root "/" because it's a relative link. This issue can me solved by just prepending by a "/" before the {{}}, but it's maybe better to automaticaly prepend the output of the perment_url getter to avoid this error.

What do you think ?

**Comment by ebursztein** [comment]
Absolute path are computed by the full path plugin:
https://github.com/ebursztein/SiteFab/blob/master/plugins/post/processor/compute_full_post_url/README.md
